language: php
sudo: false

cache:
  directories:
    node_modules
    vendor

php:
  - 5.6.37
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

install:
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source bin/travis.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh
